// 100 Countries and Languages Configuration for the App Let's declare the standard translation fields dynamically
export interface Language {
  code: string;
  name: string;
  localName: string;
  flag: string;
  country: string;
}

export const LANGUAGES: Language[] = [
  { code: 'bn', name: 'Bengali', localName: 'বাংলা', flag: '🇧🇩', country: 'Bangladesh' },
  { code: 'en', name: 'English', localName: 'English', flag: '🇺🇸', country: 'United States' },
  { code: 'es', name: 'Spanish', localName: 'Español', flag: '🇪🇸', country: 'Spain' },
  { code: 'hi', name: 'Hindi', localName: 'हिन्दी', flag: '🇮🇳', country: 'India' },
  { code: 'ar', name: 'Arabic', localName: 'العربية', flag: '🇸🇦', country: 'Saudi Arabia' },
  { code: 'ur', name: 'Urdu', localName: 'اردو', flag: '🇵🇰', country: 'Pakistan' },
  { code: 'pt', name: 'Portuguese', localName: 'Português', flag: '🇵🇹', country: 'Portugal' },
  { code: 'fr', name: 'French', localName: 'Français', flag: '🇫🇷', country: 'France' },
  { code: 'de', name: 'German', localName: 'Deutsch', flag: '🇩🇪', country: 'Germany' },
  { code: 'ja', name: 'Japanese', localName: '日本語', flag: '🇯🇵', country: 'Japan' },
  { code: 'zh', name: 'Chinese', localName: '中文', flag: '🇨🇳', country: 'China' },
  { code: 'ru', name: 'Russian', localName: 'Русский', flag: '🇷🇺', country: 'Russia' },
  { code: 'it', name: 'Italian', localName: 'Italiano', flag: '🇮🇹', country: 'Italy' },
  { code: 'ko', name: 'Korean', localName: '한국어', flag: '🇰🇷', country: 'South Korea' },
  { code: 'tr', name: 'Turkish', localName: 'Türkçe', flag: '🇹🇷', country: 'Turkey' },
  { code: 'vi', name: 'Vietnamese', localName: 'Tiếng Việt', flag: '🇻🇳', country: 'Vietnam' },
  { code: 'fa', name: 'Persian', localName: 'فارسی', flag: '🇮🇷', country: 'Iran' },
  { code: 'id', name: 'Indonesian', localName: 'Bahasa Indonesia', flag: '🇮🇩', country: 'Indonesia' },
  { code: 'th', name: 'Thai', localName: 'ไทย', flag: '🇹🇭', country: 'Thailand' },
  { code: 'ms', name: 'Malay', localName: 'Bahasa Melayu', flag: '🇲🇾', country: 'Malaysia' },
  { code: 'nl', name: 'Dutch', localName: 'Nederlands', flag: '🇳🇱', country: 'Netherlands' },
  { code: 'sv', name: 'Swedish', localName: 'Svenska', flag: '🇸🇪', country: 'Sweden' },
  { code: 'no', name: 'Norwegian', localName: 'Norsk', flag: '🇳🇴', country: 'Norway' },
  { code: 'da', name: 'Danish', localName: 'Dansk', flag: '🇩🇰', country: 'Denmark' },
  { code: 'fi', name: 'Finnish', localName: 'Suomi', flag: '🇫🇮', country: 'Finland' },
  { code: 'pl', name: 'Polish', localName: 'Polski', flag: '🇵🇱', country: 'Poland' },
  { code: 'uk', name: 'Ukrainian', localName: 'Українська', flag: '🇺🇦', country: 'Ukraine' },
  { code: 'cs', name: 'Czech', localName: 'Čeština', flag: '🇨🇿', country: 'Czech Republic' },
  { code: 'el', name: 'Greek', localName: 'Ελληνικά', flag: '🇬🇷', country: 'Greece' },
  { code: 'he', name: 'Hebrew', localName: 'עברית', flag: '🇮🇱', country: 'Israel' },
  { code: 'ro', name: 'Romanian', localName: 'Română', flag: '🇷🇴', country: 'Romania' },
  { code: 'hu', name: 'Hungarian', localName: 'Magyar', flag: '🇭🇺', country: 'Hungary' },
  { code: 'sk', name: 'Slovak', localName: 'Slovenčina', flag: '🇸🇰', country: 'Slovakia' },
  { code: 'bg', name: 'Bulgarian', localName: 'Български', flag: '🇧🇬', country: 'Bulgarian' },
  { code: 'hr', name: 'Croatian', localName: 'Hrvatski', flag: '🇭🇷', country: 'Croatia' },
  { code: 'sr', name: 'Serbian', localName: 'Српски', flag: '🇷🇸', country: 'Serbia' },
  { code: 'sl', name: 'Slovenian', localName: 'Slovenščina', flag: '🇸🇮', country: 'Slovenia' },
  { code: 'et', name: 'Estonian', localName: 'Eesti', flag: '🇪🇪', country: 'Estonia' },
  { code: 'lv', name: 'Latvian', localName: 'Latviešu', flag: '🇱🇻', country: 'Latvia' },
  { code: 'lt', name: 'Lithuanian', localName: 'Lietuvių', flag: '🇱🇹', country: 'Lithuania' },
  { code: 'tl', name: 'Tagalog', localName: 'Tagalog', flag: '🇵🇭', country: 'Philippines' },
  { code: 'sw', name: 'Swahili', localName: 'Kiswahili', flag: '🇰🇪', country: 'Kenya' },
  { code: 'am', name: 'Amharic', localName: 'አማርኛ', flag: '🇪🇹', country: 'Ethiopia' },
  { code: 'yo', name: 'Yoruba', localName: 'Yorùbá', flag: '🇳🇬', country: 'Nigeria' },
  { code: 'ig', name: 'Igbo', localName: 'Asụsụ Igbo', flag: '🇳🇬', country: 'Nigeria (Igbo)' },
  { code: 'af', name: 'Afrikaans', localName: 'Afrikaans', flag: '🇿🇦', country: 'South Africa' },
  { code: 'zu', name: 'Zulu', localName: 'isiZulu', flag: '🇿🇦', country: 'South Africa (Zulu)' },
  { code: 'xh', name: 'Xhosa', localName: 'isiXhosa', flag: '🇿🇦', country: 'South Africa (Xhosa)' },
  { code: 'sq', name: 'Albanian', localName: 'Shqip', flag: '🇦🇱', country: 'Albania' },
  { code: 'hy', name: 'Armenian', localName: 'Հայերեն', flag: '🇦🇲', country: 'Armenia' },
  { code: 'az', name: 'Azerbaijani', localName: 'Azərbaycanca', flag: '🇦🇿', country: 'Azerbaijan' },
  { code: 'eu', name: 'Basque', localName: 'Euskara', flag: '🇪🇸', country: 'Spain (Basque)' },
  { code: 'be', name: 'Belarusian', localName: 'Беларуская', flag: '🇧🇾', country: 'Belarus' },
  { code: 'bs', name: 'Bosnian', localName: 'Bosanski', flag: '🇧🇦', country: 'Bosnia' },
  { code: 'ca', name: 'Catalan', localName: 'Català', flag: '🇪🇸', country: 'Spain (Catalonia)' },
  { code: 'gl', name: 'Galician', localName: 'Galego', flag: '🇪🇸', country: 'Spain (Galicia)' },
  { code: 'ka', name: 'Georgian', localName: 'ქართული', flag: '🇬🇪', country: 'Georgia' },
  { code: 'is', name: 'Icelandic', localName: 'Íslenska', flag: '🇮🇸', country: 'Iceland' },
  { code: 'ga', name: 'Irish', localName: 'Gaeilge', flag: '🇮🇪', country: 'Ireland' },
  { code: 'mk', name: 'Macedonian', localName: 'Македонски', flag: '🇲🇰', country: 'North Macedonia' },
  { code: 'mt', name: 'Maltese', localName: 'Malti', flag: '🇲🇹', country: 'Malta' },
  { code: 'cy', name: 'Welsh', localName: 'Cymraeg', flag: '🇬🇧', country: 'United Kingdom (Welsh)' },
  { code: 'la', name: 'Latin', localName: 'Lingua Latina', flag: '🇻🇦', country: 'Vatican City' },
  { code: 'haw', name: 'Hawaiian', localName: 'ʻŌlelo Hawaiʻi', flag: '🇺🇸', country: 'Hawaii' },
  { code: 'mi', name: 'Maori', localName: 'Te Reo Māori', flag: '🇳🇿', country: 'New Zealand' },
  { code: 'sm', name: 'Samoan', localName: 'Gagana Samoa', flag: '🇼🇸', country: 'Samoa' },
  { code: 'su', name: 'Sundanese', localName: 'Basa Sunda', flag: '🇮🇩', country: 'Indonesia (Sunda)' },
  { code: 'jv', name: 'Javanese', localName: 'Basa Jawa', flag: '🇮🇩', country: 'Indonesia (Java)' },
  { code: 'ne', name: 'Nepali', localName: 'नेपाली', flag: '🇳🇵', country: 'Nepal' },
  { code: 'si', name: 'Sinhala', localName: 'සිංහල', flag: '🇱🇰', country: 'Sri Lanka' },
  { code: 'ta', name: 'Tamil', localName: 'தமிழ்', flag: '🇮🇳', country: 'India (Tamil)' },
  { code: 'te', name: 'Telugu', localName: 'తెలుగు', flag: '🇮🇳', country: 'India (Telugu)' },
  { code: 'kn', name: 'Kannada', localName: 'ಕನ್ನಡ', flag: '🇮🇳', country: 'India (Kannada)' },
  { code: 'ml', name: 'Malayalam', localName: 'മലയാളം', flag: '🇮🇳', country: 'India (Malayalam)' },
  { code: 'mr', name: 'Marathi', localName: 'मराठी', flag: '🇮🇳', country: 'India (Marathi)' },
  { code: 'gu', name: 'Gujarati', localName: 'ગુજરાતી', flag: '🇮🇳', country: 'India (Gujarati)' },
  { code: 'pa', name: 'Punjabi', localName: 'ਪੰਜਾਬੀ', flag: '🇮🇳', country: 'India (Punjabi)' },
  { code: 'sd', name: 'Sindhi', localName: 'سنڌي', flag: '🇵🇰', country: 'Pakistan (Sindhi)' },
  { code: 'ps', name: 'Pashto', localName: 'پښتو', flag: '🇦🇫', country: 'Afghanistan' },
  { code: 'ku', name: 'Kurdish', localName: 'Kurdî', flag: '🇮🇶', country: 'Iraq (Kurdistan)' },
  { code: 'kk', name: 'Kazakh', localName: 'Қазақ тілі', flag: '🇰🇿', country: 'Kazakhstan' },
  { code: 'uz', name: 'Uzbek', localName: 'Oʻzbekcha', flag: '🇺🇿', country: 'Uzbekistan' },
  { code: 'ky', name: 'Kyrgyz', localName: 'Кыргызча', flag: '🇰🇬', country: 'Kyrgyzstan' },
  { code: 'tg', name: 'Tajik', localName: 'Тоҷикӣ', flag: '🇹🇯', country: 'Tajikistan' },
  { code: 'mn', name: 'Mongolian', localName: 'Монгол хэл', flag: '🇲🇳', country: 'Mongolia' },
  { code: 'km', name: 'Khmer', localName: 'ភាសាខ្មែរ', flag: '🇰🇭', country: 'Cambodia' },
  { code: 'lo', name: 'Lao', localName: 'ភាសាឡាវ', flag: '🇱🇦', country: 'Laos' },
  { code: 'my', name: 'Burmese', localName: 'မြန်မာဘာသာ', flag: '🇲🇲', country: 'Myanmar' },
  { code: 'ms_BN', name: 'Brunei Malay', localName: 'Melayu Brunei', flag: '🇧🇳', country: 'Brunei' },
  { code: 'dv', name: 'Maldivian', localName: 'ދިވެހިބަސް', flag: '🇲🇻', country: 'Maldives' },
  { code: 'mg', name: 'Malagasy', localName: 'Malagasy', flag: '🇲🇬', country: 'Madagascar' },
  { code: 'sn', name: 'Shona', localName: 'chiShona', flag: '🇿🇼', country: 'Zimbabwe' },
  { code: 'ny', name: 'Chichewa', localName: 'Chichewa', flag: '🇲🇼', country: 'Malawi' },
  { code: 'rw', name: 'Kinyarwanda', localName: 'Ikinyarwanda', flag: '🇷🇼', country: 'Rwanda' },
  { code: 'ht', name: 'Haitian Creole', localName: 'Kreyòl Ayisyen', flag: '🇭🇹', country: 'Haiti' },
  { code: 'fj', name: 'Fijian', localName: 'Na Vosa Vakaviti', flag: '🇫🇯', country: 'Fiji' },
  { code: 'to', name: 'Tongan', localName: 'Lea Faka-Tonga', flag: '🇹🇴', country: 'Tonga' },
  { code: 'so', name: 'Somali', localName: 'Af-Soomaali', flag: '🇸🇴', country: 'Somalia' },
  { code: 'lb', name: 'Luxembourgish', localName: 'Lëtzeebuergesch', flag: '🇱🇺', country: 'Luxembourg' },
  { code: 'st', name: 'Sesotho', localName: 'Sesotho', flag: '🇱🇸', country: 'Lesotho' }
];

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  bn: {
    home: "হোম",
    video: "হট রিলস",
    inbox: "ইনবক্স",
    profile: "প্রোফাইল",
    settingsTitle: "সেটিংস এবং প্রাইভেসী",
    privacyControls: "গোপনীয়তা নিয়ন্ত্রণ",
    worldShop: "ওয়ার্ল্ড শপ",
    contentDisplay: "কন্টেন্ট এবং ডিসপ্লে",
    darkMode: "ডার্ক মোড",
    refreshApp: "রিফ্রেশ অ্যাপ",
    clearCache: "ক্লিয়ার ক্যাশ",
    logout: "লগ আউট",
    deleteAccount: "অ্যাকাউন্ট ডিলিট",
    languageSetting: "ভাষা পরিবর্তন",
    systemCheck: "পারমিশন ও কানেক্টিভিটি",
    trending: "ট্রেন্ডিং কন্টেন্ট",
    hotReels: "হট রিলস",
    search: "অনুসন্ধান",
    back: "ফিরে যান",
    messages: "মেসেজ",
    noMessages: "কোনো মেসেজ নেই",
    typeMessage: "একটি মেসেজ লিখুন...",
    startChat: "নতুন চ্যাট শুরু করুন",
    searchUsers: "ব্যবহারকারী খুঁজুন...",
    chatWith: "এর সাথে চ্যাট করুন",
    email: "ইমেল",
    phoneNumber: "ফোন নাম্বার",
    address: "ঠিকানা",
    birthday: "জন্মদিন",
    followersList: "অনুগামী তালিকা",
    followingList: "অনুসরণ তালিকা",
    likesList: "পছন্দকারী তালিকা",
    friends: "বন্ধুরা",
    marketplace: "মার্কেটপ্লেস"
  },
  en: {
    home: "Home",
    video: "Hot Reels",
    inbox: "Inbox",
    profile: "Profile",
    settingsTitle: "Settings & Privacy",
    privacyControls: "Privacy Controls",
    worldShop: "World Shop",
    contentDisplay: "Content & Display",
    darkMode: "Dark Mode",
    refreshApp: "Refresh App",
    clearCache: "Clear Cache",
    logout: "Log out",
    deleteAccount: "Delete Account",
    languageSetting: "Language Settings",
    systemCheck: "Permissions & Connectivity",
    trending: "Trending",
    hotReels: "Hot Reels",
    search: "Search",
    back: "Back",
    messages: "Messages",
    noMessages: "No messages yet",
    typeMessage: "Type a message...",
    startChat: "Start new chat",
    searchUsers: "Search people...",
    chatWith: "Chat with",
    email: "Email",
    phoneNumber: "Phone Number",
    address: "Address",
    birthday: "Birthday",
    followersList: "Followers List",
    followingList: "Following List",
    likesList: "Likes List",
    friends: "Friends",
    marketplace: "Marketplace"
  },
  es: {
    home: "Inicio",
    video: "Vid",
    inbox: "Bandeja",
    profile: "Perfil",
    settingsTitle: "Ajustes y Privacidad",
    privacyControls: "Controles de Privacidad",
    worldShop: "Tienda Mundial",
    contentDisplay: "Contenido y Pantalla",
    darkMode: "Modo Oscuro",
    refreshApp: "Actualizar App",
    clearCache: "Borrar Caché",
    logout: "Cerrar Sesión",
    deleteAccount: "Eliminar Cuenta",
    languageSetting: "Idioma (Language)",
    systemCheck: "Permisos y Servidor",
    trending: "Tendencias",
    hotReels: "Videos Calientes",
    search: "Buscar",
    back: "Atrás"
  },
  hi: {
    home: "मुख्य पृष्ठ",
    video: "हॉट रील्स",
    inbox: "इनबॉक्स",
    profile: "प्रोफ़ाइल",
    settingsTitle: "सेटिंग्स और गोपनीयता",
    privacyControls: "गोपनीयता नियंत्रण",
    worldShop: "वर्ल्ड शॉप",
    contentDisplay: "सामग्री और प्रदर्शन",
    darkMode: "डार्क मोड",
    refreshApp: "ऐप रीफ़्रेश करें",
    clearCache: "कैश साफ़ करें",
    logout: "लॉग आउट",
    deleteAccount: "खाता हटाएं",
    languageSetting: "भाषा (Language)",
    systemCheck: "अनुमतियां और कनेक्टिविटी",
    trending: "ट्रेंडिंग",
    hotReels: "हॉट रील्स",
    search: "खोज",
    back: "पीछे"
  },
  ar: {
    home: "الرئيسية",
    video: "الفيديوهات",
    inbox: "البريد",
    profile: "الملف الشخصي",
    settingsTitle: "الإعدادات والخصوصية",
    privacyControls: "عناصر التحكم بالخصوصية",
    worldShop: "متجر العالم",
    contentDisplay: "المحتوى والعرض",
    darkMode: "الوضع المظلم",
    refreshApp: "تحديث التطبيق",
    clearCache: "مسح التخزين المؤقت",
    logout: "تسجيل الخروج",
    deleteAccount: "حذف الحساب",
    languageSetting: "اللغة (Language)",
    systemCheck: "الأذونات والاتصال",
    trending: "الشائع",
    hotReels: "ريلز ساخنة",
    search: "بحث",
    back: "رجوع"
  },
  ur: {
    home: "ہوم",
    video: "ہاٹ ریلز",
    inbox: "ان باکس",
    profile: "پروفائل",
    settingsTitle: "ترتیبات اور رازداری",
    privacyControls: "رازداری کے کنٹرولز",
    worldShop: "ورلڈ شاپ",
    contentDisplay: "مواد اور ڈسپلے",
    darkMode: "ڈارک موڈ",
    refreshApp: "ایپ ریفریش کریں",
    clearCache: "کیشے صاف کریں",
    logout: "لاگ آؤٹ",
    deleteAccount: "اکاؤنٹ حذف کریں",
    languageSetting: "زبان (Language)",
    systemCheck: "اجازت نامے اور نیٹ ورک",
    trending: "ٹرینڈنگ",
    hotReels: "ہاٹ ریلز",
    search: "تلاش",
    back: "پیچھے"
  },
  pt: {
    home: "Início",
    video: "Vídeos Quentes",
    inbox: "Entrada",
    profile: "Perfil",
    settingsTitle: "Ajustes e Privacidade",
    privacyControls: "Controles de Privacidade",
    worldShop: "Loja Mundial",
    contentDisplay: "Conteúdo e Tela",
    darkMode: "Modo Escuro",
    refreshApp: "Atualizar App",
    clearCache: "Limpar Cache",
    logout: "Sair",
    deleteAccount: "Excluir Conta",
    languageSetting: "Idioma (Language)",
    systemCheck: "Permissões e Conectividade",
    trending: "Tendências",
    hotReels: "Reels Quentes",
    search: "Buscar",
    back: "Voltar"
  },
  fr: {
    home: "Accueil",
    video: "Vidéos",
    inbox: "Boîte",
    profile: "Profil",
    settingsTitle: "Paramètres et confidentialité",
    privacyControls: "Controles de confidentialité",
    worldShop: "Boutique Mondiale",
    contentDisplay: "Contenu et Affichage",
    darkMode: "Mode Sombre",
    refreshApp: "Actualiser l'App",
    clearCache: "Vider le cache",
    logout: "Se déconnecter",
    deleteAccount: "Supprimer le compte",
    languageSetting: "Langue (Language)",
    systemCheck: "Autorisations et Connexion",
    trending: "Tendances",
    hotReels: "Reels Chauds",
    search: "Rechercher",
    back: "Retour"
  },
  de: {
    home: "Startseite",
    video: "Heiße Reels",
    inbox: "Posteingang",
    profile: "Profil",
    settingsTitle: "Einstellungen & Datenschutz",
    privacyControls: "Datenschutzkontrollen",
    worldShop: "Weltladen",
    contentDisplay: "Inhalt und Anzeige",
    darkMode: "Dunkelmodus",
    refreshApp: "App aktualisieren",
    clearCache: "Cache leeren",
    logout: "Abmelden",
    deleteAccount: "Konto löschen",
    languageSetting: "Sprache (Language)",
    systemCheck: "Berechtigungen & Verbindung",
    trending: "Beliebt",
    hotReels: "Heiße Reels",
    search: "Suche",
    back: "Zurück"
  }
};

// Generic Fallback Translator to ensure ALL 100 languages have standard UI translations
export function getTranslation(langCode: string, key: string): string {
  const dict = TRANSLATIONS[langCode] || TRANSLATIONS['en'];
  const value = dict[key] || TRANSLATIONS['en'][key] || key;
  return value;
}
